name: NuGet
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 'master'
      - 'release-*'

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_PACKAGE_SOURCE: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
    steps:
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch full history for NBGV
      - uses: dotnet/nbgv@v0.4
        id: nbgv

      - run: mkdir packages
      - run: dotnet pack -c Release -o packages WinFormsUI
      - run: dotnet pack -c Release -o packages WinFormsUI.ThemeVS2005
      - run: dotnet nuget push -k "${{ secrets.GITHUB_TOKEN }}" -s "${{ env.GITHUB_PACKAGE_SOURCE }}" "packages\DockPanelSuite.${{ steps.nbgv.outputs.NuGetPackageVersion }}.nupkg"
      - run: dotnet nuget push -k "${{ secrets.GITHUB_TOKEN }}" -s "${{ env.GITHUB_PACKAGE_SOURCE }}" "packages\DockPanelSuite.ThemeVS2005.${{ steps.nbgv.outputs.NuGetPackageVersion }}.nupkg"
